---
title: "generate_phers"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{generate_phers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  retina = 2)

foreach::registerDoSEQ()
```

```{r setup}
library('phers')
library('data.table')
library('iterators')
library('ggplot2')

# doParallel::registerDoParallel() # register a parallel backend to minimize runtime
```

```{r}
demoSample = data.table(
  person_id = 1:5,
  sex = c('F', 'M', 'M', 'F', 'F'))

icdSample = data.table(
  person_id = c(rep(1L, 3), rep(2L, 4), rep(3L, 2), 4),
  icd = c('365', '366', '734', '759.82', '524.0', '718.4', '441', '366', '734', '441'),
  flag = 9)

set.seed(1) 
npop = 5
gene1 = 'FBN1'
nvar = uniqueN(geneVarMap[gene == gene1]$vid)
genoSample = data.table(person_id = 1:npop)
genos = replicate(
  nvar, sample(c(0, 1, 2), replace = TRUE, size = npop, prob = c(80, 15, 5)))
colnames(genos) = unique(geneVarMap[gene == gene1]$vid)
genos = as.data.table(genos)
genoSample = cbind(genoSample, genos)
```

```{r}
# map ICD codes to phecodes
phecodeOccurrences = getPhecodeOccurrences(icdSample)

# calculate weights 
weights = getWeights(demoSample, phecodeOccurrences)

# vector of OMIM disease IDs to calculate PheRS for
diseaseIds = 154700

# mape diseases to phecodes
diseasePhecodeMap = mapDiseaseToPhecode()

# calculate PheRS
scores = getScores(
  demoSample, phecodeOccurrences, weights, diseasePhecodeMap[disease_id == diseaseIds])
 
# calculate residual PheRS
rscores = getResidualScores(demoSample, scores, glmFormula = as.formula(~ sex))

# calculate PheRS using pre-calculated weights
pWeights = getWeights(demoSample, phecodeOccurrences, preCalcWeights = TRUE)
scores = getScores(
  demoSample, phecodeOccurrences, pWeights, diseasePhecodeMap[disease_id == diseaseIds])
```

perform genotype association 
```{r}
demos = demoSample[, .(person_id, sex)]
diseaseVariantMap = merge(
  diseaseInfo[disease_id %in% unique(scores$disease_id)], geneVarMap, 
  by = 'gene')[, .(disease_id, gene, vid)]

genoStats = getGeneticAssociations(
  scores, genoSample, demos, diseaseVariantMap, glmFormula = as.formula(~ sex), 
  modelType = 'additive')

genoStats = merge(geneVarMap[, .(gene, vid)], genoStats, by = 'vid')

genoStats
```


run positive control analysis
```{r}
dxStatus = getDxStatus(demoSample, icdSample)

plotInput = merge(rscores, dxStatus, by = c('person_id', 'disease_id'))

ggplot(plotInput) + geom_boxplot(aes(x = factor(dx_status), y = r_score))
```
